ansible_python_interpreter: auto_silent
ansible_ssh_host: "{{ inventory_hostname }}.host.neontech.dev"
ansible_ssh_private_key_file: ./.ssh/{{ inventory_hostname }}-{{ ansible_ssh_user }}_ed25519
ansible_ssh_user: root
