mysql_server_docker_version: 9.0.1@sha256:48ce690effadbc5042c7f3edddeac50baf190d59a438b6a92ed714c3dea1ea19
mysql_server_step_docker_version: 0.28.2@sha256:dbe894c2d146b7389cc2e1e1d14cccd03f8c765a6eeb957f3340333c2f86a767
# server
mysql_server_port: 3306
mysql_server_flags: []
# root
mysql_server_root_username: root
mysql_server_root_password: "{{ mandatory(msg='default secret') }}"
# replication
mysql_server_replication_username: replication
mysql_server_replication_password: "{{ mandatory(msg='default secret') }}"
mysql_server_replication_mode: master
# master
mysql_server_master_host: localhost
mysql_server_master_port: "{{ mysql_server_port }}"
# tls
mysql_server_tls: false
mysql_server_tls_username: tls
mysql_server_tls_password: "{{ mandatory(msg='default secret') }}"
mysql_server_tls_domains: localhost
mysql_server_tls_ca_host: ca
mysql_server_tls_ca_port: 443
mysql_server_tls_ca_fingerprint: "{{ mandatory(msg='default value') }}"
mysql_server_tls_acme_rfc2136_ip: 127.0.0.1
mysql_server_tls_acme_rfc2136_port: 53
mysql_server_tls_acme_rfc2136_name: acme
mysql_server_tls_acme_rfc2136_secret: "{{ mandatory(msg='default secret') }}"
mysql_server_tls_acme_rfc2136_algorithm: HMAC-SHA256
