mysql_server_docker_version: sha256:0c61a2f3861cddc96610eb3b92dea4f07471a21f5423d18df03dc476dc22e9e4 # 9.0.1
mysql_server_flags: []
mysql_server_root_username: root
mysql_server_root_password: "{{ mandatory(msg='default secret') }}"
mysql_server_replication_username: replication
mysql_server_replication_password: "{{ mandatory(msg='default secret') }}"
mysql_server_master_host: mysql
mysql_server_replication_mode: master
