mysql_server_docker_version: 9.0.1@sha256:48ce690effadbc5042c7f3edddeac50baf190d59a438b6a92ed714c3dea1ea19
# server
mysql_server_flags: []
# root
mysql_server_root_username: root
mysql_server_root_password: "{{ mandatory(msg='default secret') }}"
# replication
mysql_server_replication_username: replication
mysql_server_replication_password: "{{ mandatory(msg='default secret') }}"
mysql_server_replication_mode: master
# master
mysql_server_master_host: localhost
mysql_server_master_port: 3306
