- name: Create stack directory
  ansible.builtin.file:
    path: "{{ docker_rootless_user.home }}/stacks/postgresql"
    owner: "{{ docker_rootless_user.name }}"
    group: "{{ docker_rootless_user.name }}"
    mode: "0755" # drwxr-xr-x
    state: directory
  register: postgresql_server_stack

- name: Deploy stack.yml
  ansible.builtin.template:
    src: roles/postgresql_server/templates/stack.yml.j2
    dest: "{{ postgresql_server_stack.path }}/stack.yml"
    owner: "{{ docker_rootless_user.name }}"
    group: "{{ docker_rootless_user.name }}"
    mode: "0644" # -rw-r--r--

- name: Deploy postgresql-password
  ansible.builtin.copy:
    content: "{{ postgresql_server_password }}"
    dest: "{{ postgresql_server_stack.path }}/postgresql-password"
    owner: "{{ docker_rootless_subuid + 1001 - 1 }}"
    group: "{{ docker_rootless_user.name }}"
    mode: "0600" # -rw-------
  notify:
    - Restart PostgreSQL

- name: Deploy replication-password
  ansible.builtin.copy:
    content: "{{ postgresql_server_replication_password }}"
    dest: "{{ postgresql_server_stack.path }}/replication-password"
    owner: "{{ docker_rootless_subuid + 1001 - 1 }}"
    group: "{{ docker_rootless_user.name }}"
    mode: "0600" # -rw-------
  notify:
    - Restart PostgreSQL

- name: Create and start PostgreSQL
  become: true
  become_user: "{{ docker_rootless_user.name }}"
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ docker_rootless_user.name }}
    DOCKER_HOST: unix:///run/user/{{ docker_rootless_user.name }}/docker.sock
  community.docker.docker_compose_v2:
    project_src: "{{ postgresql_server_stack.path }}"
    files: [stack.yml]
    project_name: postgresql
    state: present
