$ANSIBLE_VAULT;1.1;AES256
65343731646235616462636466343638623363303463623035626634333265643337623837323036
6465613435376539633534383262326632643162333132360a613363313065303735636666616438
32373738336139336239373331373338313962393533323463353963306538333435373434323564
3231366335343533610a653662303537646135616436613562616265663166366235663136303839
35666634313736353663313437653063663431663865373234383965663039336663353735663363
31663930386635363234663034393164616138316664393830623136356538363335653631613366
31356637326237623865333734363239333065376131346431643437336231373662386633313839
39633861306264396165313166623235313333333731623237393065323364323565336333633931
39343064333063643463323636396130353935383836353133663430383731616237356332343431
3761646261386135636634636462363361313035316564656363
