# API
pve_lxc_api_host: localhost
pve_lxc_api_port: 8006
pve_lxc_api_user: root@pam
pve_lxc_api_token_id: "{{ mandatory(msg='default value') }}"
pve_lxc_api_token: "{{ mandatory(msg='default secret') }}"

# General
pve_lxc_node: "{{ inventory_hostname }}"
pve_lxc_vmid: "{{ mandatory(msg='default value') }}"
pve_lxc_hostname: "{{ mandatory(msg='default value') }}"
pve_lxc_ssh_public_key_file: "{{ mandatory(msg='default value') }}"

# Template
pve_lxc_template: debian-12-standard_12.7-1_amd64.tar.zst
pve_lxc_template_type: vztmpl
pve_lxc_os_type: debian

# Storage
pve_lxc_storage: "{{ mandatory(msg='default value') }}"
pve_lxc_storage_fs: "{{ mandatory(msg='default value') }}"

# Disks
pve_lxc_disk_volume_storage: "{{ pve_lxc_storage }}"
pve_lxc_disk_volume_size: 8 # GiB

# CPU
pve_lxc_cpu_cores: 1

# Memory
pve_lxc_memory: 512 # MB
pve_lxc_memory_swap: 512 # MB

# Network
pve_lxc_interfaces: {}
