# API
pve_lxc_api_host: localhost
pve_lxc_api_port: 8006
pve_lxc_api_user: root@pam
pve_lxc_api_token_id: "{{ mandatory(msg='default value') }}"
pve_lxc_api_token: "{{ mandatory(msg='default secret') }}"

# General
pve_lxc_node: "{{ mandatory(msg='default value') }}"
pve_lxc_vmid: "{{ mandatory(msg='default value') }}"
pve_lxc_hostname: "{{ inventory_hostname }}"
pve_lxc_ssh_public_key_file: "{{ mandatory(msg='default value') }}"

# Template
pve_lxc_template: debian-13-standard_13.1-2_amd64.tar.zst
pve_lxc_template_type: debian

# Storage
pve_lxc_storage: "{{ mandatory(msg='default value') }}"
pve_lxc_storage_fs: "{{ mandatory(msg='default value') }}"

# Disks
pve_lxc_disk_volume_storage: "{{ pve_lxc_storage }}"
pve_lxc_disk_volume_size: 16 # GiB

# CPU
pve_lxc_cpu_cores: 1

# Memory
pve_lxc_memory: 1024 # MB
pve_lxc_memory_swap: 0 # MB

# Network
pve_lxc_interfaces: {}

# Startup/Shutdown Order
pve_lxc_order: 1
pve_lxc_startup: 0 # Seconds
pve_lxc_shutdown: 60 # Seconds
