chrony_conf: /etc/chrony.conf
chrony_servers:
  - time.cloudflare.com iburst nts
chrony_driftfile: /var/lib/chrony/drift
chrony_makestep_threshold: 0.1
chrony_makestep_updates: 3
chrony_allows: []
chrony_ntsdumpdir: /var/lib/chrony
chrony_logdir: /var/log/chrony
