$ANSIBLE_VAULT;1.1;AES256
31643031613364393433323861396565643934626266396433386164393765363863653863633961
3361306662623334393934373939363830336338666564380a636638313766373465636164326231
39333730396262396361326565633238313362323564353436633762663166366164333662646364
3266636131633966370a356432353066626664303066323939323237653330643264613430623562
63336636303531383231363537383830343135656539626532306439353963613830323738353261
34383861643066386161633731663533646533333738363638666334353561313233356136363964
383632313664316334616336653564313733
