$ANSIBLE_VAULT;1.1;AES256
36623963353939633137653938343930663863386434623362316531326331653338313961616139
6661363332376362383932623930636465383666613630330a633035383133616435613532353333
65336466393363316237626438343636613731376330663130316530373766616663386431643764
3664303732373634620a663366623836376137366536323138623265353537653461346231633230
61626663343235306366353938303235343165653265663237383532386562356333623562636336
63633564356163343263373465346535393262663261303166613539323465333139373162626165
61663562643064323966343837666134643839333132333532346434663332393534393333646661
37613861313565333765613463663937396266633263636633643138326336353466656335313631
36666437653239363837653430303362373366316433646130393762633966376161306334313232
32363639373861626439653233373038303034306533333363353236376631396463343464656232
376139336632306530623533303433313366
