$ANSIBLE_VAULT;1.1;AES256
32326430343137613438663235346364663136653664613964333733663237616238316133633036
3365386562373933396231396532353762623262326432310a666234343434653165346337666261
62623434373937626564373665316538656664373331393431333730636365326139383234363932
3861626536323361390a653064663366666437613238373762303566383931343765316565343265
65323065623262656530376265643739333534386534353463663466313030343736313335363235
34666435636331656233396332306139366362623663386530636433396164656535623363623830
66386261393361616137383234633661316337346130636261616330383932626364666635343063
39306337343132383966636439343461653463313538376361613036336161353235356633636266
61656439333337633937323130643337333230306230336266346663616237376434616661306139
31383639623937613561633637306439633139323264363930313030633364353262313638373234
616165323239333737366436633565333737
