$ANSIBLE_VAULT;1.1;AES256
38393936353363323663666366636539646632323665656232643663343536333830343435343839
3533633231313237383034656430663435343366656134310a373465303231363830343136643036
33313861383838386663313330313864623965643361346135393530666231333734326339663232
3635313264653136360a316466386530363039386531616437393938616336323663356430656136
62396331343632323766613561353034376663363166336431663035353261313239373963363038
62333535363966613037346662623332353338333036623036316362616266663439313861376233
61616261613661643538323064616534386261386565636134303435363464633135393164383362
35613963653530636536313739326662393532616461386134633066366232666364616330356633
39656538616531303436393865623763376632336338316432373936623864656639626462623831
34633837336433613631633764336332383538313461366664333963353361633561633666623538
633836663834303262346261383535376339
