$ANSIBLE_VAULT;1.1;AES256
30383964323737653564373661323135623534313439626334383035303166656131643732353063
6662393234633861623036613430383064333333623738320a303763306164646165313635376265
36366664613334363134313236303361393735623663306331393639393135646535636665333661
3262623864396234310a653935666237663630346433613037316364306562363639346463633833
65353139343062633765613438656164623731653461633832386363626333393761646434336664
66383130643961623933393361663132663330353633323932623630396535373734373834313162
62326134613562623964663435643833373661656361633833313336643336326261626333373964
62373833396137373364663730626537333061616538393961646564393639363536316136393331
36376333653837363930633938633062616435613937643162396437313230323166
