mariadb_server_docker_version: 11.4.4@sha256:0b4992ca2e7fd36f8b4ba57d6cd43d38dcc6d8c37d471c8bf63594b516175115
mariadb_server_step_docker_version: 0.28.2@sha256:dbe894c2d146b7389cc2e1e1d14cccd03f8c765a6eeb957f3340333c2f86a767
# server
mariadb_server_port: 3306
mariadb_server_flags: []
# root
mariadb_server_root_username: root
mariadb_server_root_password: "{{ mandatory(msg='default secret') }}"
# replication
mariadb_server_replication_username: replication
mariadb_server_replication_password: "{{ mandatory(msg='default secret') }}"
mariadb_server_replication_mode: master
# master
mariadb_server_master_host: localhost
mariadb_server_master_port: "{{ mariadb_server_port }}"
# tls
mariadb_server_tls: false
mariadb_server_tls_username: tls
mariadb_server_tls_password: "{{ mandatory(msg='default secret') }}"
mariadb_server_tls_domains: [localhost]
mariadb_server_tls_ca_host: ca
mariadb_server_tls_ca_port: 443
mariadb_server_tls_ca_fingerprint: "{{ mandatory(msg='default value') }}"
mariadb_server_tls_acme_rfc2136_ip: 127.0.0.1
mariadb_server_tls_acme_rfc2136_port: 53
mariadb_server_tls_acme_rfc2136_name: acme
mariadb_server_tls_acme_rfc2136_secret: "{{ mandatory(msg='default secret') }}"
mariadb_server_tls_acme_rfc2136_algorithm: HMAC-SHA256
