# server
mysql_server_flags: [--max-connections=1000]
# root
mysql_server_root_username: root
mysql_server_root_password: "{{ vault_mysql_server_root_password }}"
# replication
mysql_server_replication_username: replication
mysql_server_replication_password: "{{ vault_mysql_server_replication_password }}"
mysql_server_replication_host: mysql{{ mysql_server_node_id }}.service.neontech.dev
# master
mysql_server_master_host: "{{ mysql_server_host }}"
mysql_server_master_port: 3306
# tls
mysql_server_tls: true
mysql_server_tls_username: "{{ mysql_server_root_username }}"
mysql_server_tls_password: "{{ mysql_server_root_password }}"
mysql_server_tls_domains: "{{ mysql_server_master_host }},{{ mysql_server_replication_host }}"
mysql_server_tls_ca_host: "{{ ca_host }}"
mysql_server_tls_ca_port: "{{ ca_port }}"
mysql_server_tls_ca_fingerprint: "{{ ca_fingerprint }}"
mysql_server_tls_acme_rfc2136_ip: "{{ dns_server }}"
mysql_server_tls_acme_rfc2136_name: acme_{{ mysql_server_host }}
mysql_server_tls_acme_rfc2136_secret: "{{ vault_mysql_server_tls_acme_rfc2136_secret }}"
