$ANSIBLE_VAULT;1.1;AES256
32313130326233346132393137343630666235646235613630343230363833646464636332613566
3333643338386361613834643237336361656363353537650a633364333666613033653534363631
65343264366262316635326465326433326136626536633436316161323161346664633962316137
3239356538326263640a353036353165376364376335363335656433353831386237623433333634
65666239383639333732343264396139343830333261363466663036353634323665653435396630
65343130306164633232653863653436333836383137646133386161643933646463383233383632
31626233396536643865373036386464326661653361343032346239313933666134313331343837
64626561303665643666643836396462336666393730373237653262626663636231366566303432
64306266316233316239333530366532373538666238633731633663326664396433346131626662
34393736666132306436636365666135383565303964643539383762613635633333356561636233
66373038336265323036306335383565663239346532386562326561626262646433346339623765
66633638396565663038663964376335623163313965326134613733386433343562646530643839
36623466376136663933623365353164316263633335303865326666383365373234663164643366
39316631353336343735396438353566613039323230313963323965633463333930383836666530
64313635656532386666613539333432626364383766343066336232613065666265323338363665
62653761336331643865366332666561653166396463643066623530646531333766613466363362
33313934316165326332306466663262626632656331323137646332363737393963613438376466
33313738306535613938393730336538663736643831636663626461626233323831386462303330
30643165653736383131616335656530653465633365636266613937303937306539306139653761
62353164653532326637633062633834343162303435303661646635653835623664636334643963
3833
