$ANSIBLE_VAULT;1.1;AES256
37383232316537633437393436646466613734313861386339376363613435623263633736326232
3162383630333731663533326238303531376462376163640a353839636365323236393763336662
39363133323930386266626536313761336632636239643965306164396637613238383266363239
6236306361393432310a373133343133346336396132646661303338323062313332666163396635
32313638313034616165333438376233303861333338353936386232323436346563623931653733
64613765323032376634626166663136393235363230663463643161323565396230623936636634
61623731393732623735376131386130396662626630623631613937346465633336646534663031
65376361373563376237663337666430383065303435636161323436393239313661353139623536
61373533316664323539353436633564626130376537353432313435366633653365346336643234
35373332366165646561333161353765376630353963353563393165643937323966383234326562
66353238656664353236643137616532663336393065613561396262356266663730363736316665
38636166303162623935366164376338386338323234366437666631653636356664363534643966
38316633346631646539303538323636396438383336613634336638303239303535623463343630
38393965383065363930366639386431313961633961356437393638623737333565613538333666
35303161353834656138376661656162313464336135386538303036343265353639393864393932
64333762633430336265
