- name: Save iptables (IPv4)
  ansible.builtin.command: /etc/init.d/iptables save
  changed_when: true
  notify:
    - Commit

- name: Save iptables (IPv6)
  ansible.builtin.command: /etc/init.d/ip6tables save
  changed_when: true
  notify:
    - Commit
