$ANSIBLE_VAULT;1.1;AES256
39323166646635363330336138393338376135633239336564376261383862363234623937393631
3766313230333539643338613138613032633462356139380a646338396361383931323861626630
37373463346230633132656436396539353735313764613535353665323033646631663634316532
6335613632663932610a373438643665313237333036376332643439656234396336393038366538
31393339333533623036633838343530666564383634326262626131393930623632653337633166
30653631666434626561643736326566363965383039336261346434626438373432666561373933
36363161343339626430633162326630666435633465646563623430383963383431653039373837
35643333626366316537383735383664376138376561653161323133633634656137376663386539
63303765363638343565303335663562353836393366316666623330353639653133336563613064
64376632383834666137323136613838353961346263656665653437323733343433333735643937
34303463656132646135366434383430363936663739353532656565643438363366323962386164
31336633616436306536663434303934336233316365353633383436376266633264393933383066
32616163636265323739313865666433613862376539323962613636383739306237613731393132
35643837336638306237333661656363623331653933366330643762653334383132333262383237
32306263303435303638353231616134333465656533336365623636636333323363343135633935
36383664356439663237
