$ANSIBLE_VAULT;1.1;AES256
38363838653235373236326664363266383863353634303763356665336261646630363838643265
6530323836373362663938346165643639363665626364390a653939663438343336373062323562
36636534353331386133343531363138646439333438393861363339303637656533316536653237
3462626533636466370a643833393836393831346434373064616233353736393465663263613237
37366638613562626439313364396662393136373962623766383663316362343564396437376562
62643861356564313563343130353037316464336134613264636333396565306334366130303365
31636537336361653934393232316461323263386131333136306532633438303539656462323462
39396266653736366630336236313163373435306438343264366139383436393462376339333064
3733
