ansible_python_interpreter: auto_silent

# Become
ansible_become_method: su

# SSH
ansible_ssh_args: -o UserKnownHostsFile=./ssh/known_hosts
ansible_ssh_user: root
ansible_ssh_host: "{{ inventory_hostname }}.host.neontech.dev"
ansible_ssh_private_key_file: ./.ssh/{{ inventory_hostname }}_{{ ansible_ssh_user }}_ed25519

# CA
ca_host: ca.service.neontech.dev

# MySQL
mysql_server_host: mysql.service.neontech.dev

#region PostgreSQL
# Server
postgresql_server_host: postgresql.service.neontech.dev
postgresql_server_port: 5432
postgresql_server_username: postgres
postgresql_server_password: "{{ vault_postgresql_server_password }}"
postgresql_server_database: postgres
# Client
postgresql_client_login_host: "{{ postgresql_server_host }}"
postgresql_client_login_port: "{{ postgresql_server_port }}"
postgresql_client_login_username: "{{ postgresql_server_username }}"
postgresql_client_login_password: "{{ postgresql_server_password }}"
postgresql_client_login_database: "{{ postgresql_server_database }}"
#endregion

# Redis
redis_server_host: redis.service.neontech.dev
