#region MySQL
# server
mysql_server_flags: [--max-connections=1000]
# root
mysql_server_root_username: root
mysql_server_root_password: "{{ vault_mysql_server_root_password }}"
# replication
mysql_server_replication_username: replication
mysql_server_replication_password: "{{ vault_mysql_server_replication_password }}"
# master
mysql_server_master_host: "{{ mysql_server_host }}"
mysql_server_master_port: 3306
#endregion

#region PostgreSQL
# replication
postgresql_server_replication_username: replication
postgresql_server_replication_password: "{{ vault_postgresql_server_replication_password }}"
postgresql_server_replication_host: postgresql{{ postgresql_server_node_id }}.service.neontech.dev
# master
postgresql_server_master_host: "{{ postgresql_server_host }}"
postgresql_server_master_port: 5432
# tls
postgresql_server_tls: true
postgresql_server_tls_domains: "{{ postgresql_server_master_host }},{{ postgresql_server_replication_host }}"
postgresql_server_tls_ca_host: "{{ ca_host }}"
postgresql_server_tls_ca_port: "{{ ca_port }}"
postgresql_server_tls_ca_fingerprint: "{{ ca_fingerprint }}"
postgresql_server_tls_ca_database_name: "{{ ca_database_name }}"
postgresql_server_tls_ca_database_user: "{{ ca_database_user }}"
postgresql_server_tls_acme_rfc2136_ip: "{{ dns_server }}"
postgresql_server_tls_acme_rfc2136_name: acme_{{ postgresql_server_host }}
postgresql_server_tls_acme_rfc2136_secret: "{{ vault_postgresql_server_tls_acme_rfc2136_secret }}"
#endregion

#region Redis
# server
redis_server_username: default
redis_server_password: "{{ vault_redis_server_password }}"
# replication
redis_server_replication_host: redis{{ redis_server_node_id }}.service.neontech.dev
# master
redis_server_master_host: "{{ redis_server_host }}"
# tls
redis_server_tls: true
redis_server_tls_username: tls
redis_server_tls_password: "{{ vault_redis_server_tls_password }}"
redis_server_tls_domains: "{{ redis_server_master_host }},{{ redis_server_replication_host }}"
redis_server_tls_ca_host: "{{ ca_host }}"
redis_server_tls_ca_port: "{{ ca_port }}"
redis_server_tls_ca_fingerprint: "{{ ca_fingerprint }}"
redis_server_tls_acme_rfc2136_ip: "{{ dns_server }}"
redis_server_tls_acme_rfc2136_name: acme_{{ redis_server_host }}
redis_server_tls_acme_rfc2136_secret: "{{ vault_redis_server_tls_acme_rfc2136_secret }}"
# users.acl
redis_server_administrator_username: administrator
redis_server_administrator_password: "{{ vault_redis_server_administrator_password }}"
#endregion
