$ANSIBLE_VAULT;1.1;AES256
38363662373064326437373361383333373262383539613361333839623537656161383838616337
3138353933663736623436346432616633643634306637630a336232306166383562313463396565
36626538326339623132316133393034323633383433623634616134633866326533326531643635
3538326566376433630a656538666235343333346138383462333961623132653531376230626431
35626364663931363631336166646433343062653963383963623131373764383337646239616133
35383930386236623866386537333338356261323838313335336534633662663736303461303463
65633731646436306332366162666239366337386562626234616463393266616531646437656237
36353530643566373563663861383466393762303836336532623131373862653465383266323036
65353534303966303238643035326338363130376561396232613463636332333933333432396132
61623463356363323236376530626361386239636566373636653335633162316630373839616532
36663866613736393239643633393433323664383334363863313535386536366365363739333264
65336461646537306439363532393066646333326164623934636366343131633731393030396533
32393564613533646137303130393437306436646234663237636366613437343662316533653066
66616630346266396133666237623734373739373230376665313638633531363734313939653465
32343633316538643061613535613331636564623439383335643439326137656463333237363837
30343234643735336134616137656532343866336136313732663166363039313832636163353363
35366131323033656231356564313335303364353035366436396264366331336235393064663831
39366162376661646335366335333338656462303232303864646337336431346130616639333964
31363031306436373461326233336635383732633032323333343665323433383064343835306236
37363066323139633231643734366635396362316161643937356138353661393261383331656338
61393336623632613631643534333031363239613465336639396233313135393732306239623766
66343835636430656364313265373036663336353130363762626363623738616538636163323030
34326637653166386133366134336362343066386538336563323139383537373966656237666430
37323436363065626237383435373661323131343233623865306166313734643339383932393738
61313332616538393565336137653863373130626230353133616232326236636462363862643161
64376335383964663237623461393932343432323537646633353865653262663663313031333139
31333663303938323366393064336435653764303039653531383466383235623932306333333839
65616639646366383838346132616234656330343939383361343434656161623463306262323338
3863
