$ANSIBLE_VAULT;1.1;AES256
64613865616563653434353366386430666163353962646463626231393935346232333230393164
6265613662663338356330343237656338356534353661620a356134363636353731633939366166
39366137636562303963383639376462663032373838326166646332343764343439636164666533
3739643666336136310a363863306630613036333435346536353338376139656139656430356437
64626363346534616532343739326262666561383339626134313333636537383533356436303431
38616636313135333866393236343261663833393462343465646665336465316566356530303530
36323933303432303433626538636237386665306237343536633133666561616465636636316539
30613836643363333833613031626238646434323365666562303062323734366135303161313036
35306361343834363562333632363164333861326331613830663039363438623038323537386566
64343832303464643534653037666336616533613836653635636639663835353731666361663164
65373937653362336138636339613639653837306134323266353061616336303733396536646531
66396434373635613132313065643763636337653366623339333062356630613931373364643530
34306135623534313465383731336565303638333639393530376439643362326361623139346134
65316566633637653633383131373864656331613766326361313635633162313738613961343233
62393562346166363663363164643162663764643939653033333466623430656338343032323065
31383139643738626238383963396230646164393332613165373864346266376164303764316436
36663664353461626464653161316563313966636330623766343635613164336433373739653261
34353130326131393637346364616533633835353930303162343436393363306265656134613137
31313765386633336666353431653765333333636232623738626630353463653730323361363636
34383965323533613130346261633631353830353365613734623034356464313565373334643031
37303731303263656130663135316330306661386533356530626361633436373166313330386338
66343632383935663961666262653831326631343930663761326333386234373965303839383262
30353439383134306130633934646530343462303435366666373134323633316463643936363532
31326138303637353361643462663734386633623162363138303136333562306632316561393539
6237
