$ANSIBLE_VAULT;1.1;AES256
30646632343033326332333233666334313964666339643566363335363466616362626461653563
6665613933393861323130616361653438316164366333640a396537386433306136396239623536
35626261636136346336376139633738323430336232303238356237353630336662303064313534
3936383131343138350a326539656161656236383964303866613736653837386462646238353339
66633530323464633037306266663565323462613666653732303866663538623233623262616134
66633636653062663265306433633066623864313661633133316565343830393935353638396462
63346539336263623631363162653866343732646163656664646337313235393936623565643730
37646164376230396435343462373963303465323263353332313764396336333362653564313230
31643564353564386534623038393165663932376163353566323137393063326637386366353633
61373037643235633933666165646362336533303133356135303432363230623462353738303233
33333361343361653133396465643439343634353963396533386530396338326631323863613034
39366639343632363039616632303163336663363738323833643466643363646331333665366438
39666563326238323532616635613139373434663336323234663532643237353036306238376433
34633239366336313561306236366332623432626238666662303361646331646665373631623630
63383838623035623562363236613336633831363035373765636135373861653935323533656265
32373534613961303039383332316536333930303532333835643536636231643063313064346230
31653932366633336435376639643532343462353363333665623932363236363066663934633738
36333234393739633238386462346632386164363032633964376437626265366439613838666365
66623531626561333930633530343734353332663030313631316565313663323130383131373464
31383861373562633134
