- name: Create stack directory
  ansible.builtin.file:
    path: "{{ docker_rootless_user.home }}/stacks/mariadb"
    owner: "{{ docker_rootless_user.name }}"
    group: "{{ docker_rootless_user.name }}"
    mode: "0755" # drwxr-xr-x
    state: directory
  register: mariadb_server_stack

- name: Deploy stack.yml
  ansible.builtin.template:
    src: roles/mariadb_server/templates/stack.yml.j2
    dest: "{{ mariadb_server_stack.path }}/stack.yml"
    owner: "{{ docker_rootless_user.name }}"
    group: "{{ docker_rootless_user.name }}"
    mode: "0644" # -rw-r--r--

- name: Deploy root-password
  ansible.builtin.copy:
    content: "{{ mariadb_server_root_password }}"
    dest: "{{ mariadb_server_stack.path }}/root-password"
    owner: "{{ docker_rootless_subuid + 1001 - 1 }}"
    group: "{{ docker_rootless_user.name }}"
    mode: "0600" # -rw-------
  notify:
    - Restart MariaDB

- name: Deploy replication-password
  ansible.builtin.copy:
    content: "{{ mariadb_server_replication_password }}"
    dest: "{{ mariadb_server_stack.path }}/replication-password"
    owner: "{{ docker_rootless_subuid + 1001 - 1 }}"
    group: "{{ docker_rootless_user.name }}"
    mode: "0600" # -rw-------
  notify:
    - Restart MariaDB

- name: Deploy TLS
  when: mariadb_server_tls
  block:
    - name: Deploy mariadb-tls
      ansible.builtin.copy:
        src: roles/mariadb_server/files/mariadb-tls/
        dest: "{{ mariadb_server_stack.path }}/mariadb-tls/"
        owner: "{{ docker_rootless_user.name }}"
        group: "{{ docker_rootless_user.name }}"
        mode: preserve
        directory_mode: "0755" # drwxr-xr-x
    - name: Deploy tls-password
      ansible.builtin.copy:
        content: "{{ mariadb_server_tls_password }}"
        dest: "{{ mariadb_server_stack.path }}/tls-password"
        owner: "{{ docker_rootless_subuid + 1001 - 1 }}"
        group: "{{ docker_rootless_user.name }}"
        mode: "0600" # -rw-------
      notify:
        - Restart MariaDB
    - name: Deploy acme-rfc2136.ini
      ansible.builtin.template:
        src: roles/mariadb_server/templates/acme-rfc2136.ini.j2
        dest: "{{ mariadb_server_stack.path }}/acme-rfc2136.ini"
        owner: "{{ docker_rootless_subuid + 1001 - 1 }}"
        group: "{{ docker_rootless_user.name }}"
        mode: "0600" # -rw-------
      notify:
        - Restart MariaDB

- name: Create and start MariaDB
  become: true
  become_user: "{{ docker_rootless_user.name }}"
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ docker_rootless_user.name }}
    DOCKER_HOST: unix:///run/user/{{ docker_rootless_user.name }}/docker.sock
  community.docker.docker_compose_v2:
    project_src: "{{ mariadb_server_stack.path }}"
    files: [stack.yml]
    state: present
