nginx_server_docker_version: 1.27.3@sha256:ef4035c5334e980debdfc25be644b5548739ec7f058e4f15feb0966addcda714
nginx_server_step_docker_version: 0.28.2@sha256:dbe894c2d146b7389cc2e1e1d14cccd03f8c765a6eeb957f3340333c2f86a767
# tls
nginx_server_tls: false
nginx_server_tls_domains: [localhost]
nginx_server_tls_ca_host: ca
nginx_server_tls_ca_port: 443
nginx_server_tls_ca_fingerprint: "{{ mandatory(msg='default value') }}"
nginx_server_tls_acme_email: "{{ mandatory(msg='default value') }}"
nginx_server_tls_acme_cloudflare_token: "{{ mandatory(msg='default secret') }}"
