mariadb_version: 12.1

# User
mariadb_user_name: "{{ ansible_user_id }}"
mariadb_user_id: "{{ ansible_user_uid }}"
mariadb_group_name: "{{ mariadb_user_name }}"
mariadb_group_id: "{{ mariadb_user_id }}"

# Server
mariadb_bind_address: null
mariadb_max_connections: null

# Login
mariadb_username: root
mariadb_password: "{{ mandatory(msg='default secret') }}"

# SSL
mariadb_ssl_ca: null
mariadb_ssl_certificate: /etc/mysql/certificates/fullchain.pem
mariadb_ssl_certificate_key: /etc/mysql/certificates/privkey.pem
