# tls
nginx_server_tls: true
nginx_server_tls_domains:
  - neontech.dev
  - "*.neontech.dev"
  - "*.internal.neontech.dev"
nginx_server_tls_ca_host: "{{ ca_host }}"
nginx_server_tls_ca_port: "{{ ca_port }}"
nginx_server_tls_ca_fingerprint: "{{ ca_fingerprint }}"
nginx_server_tls_acme_email: email@neontech.dev
nginx_server_tls_acme_cloudflare_token: "{{ vault_nginx_server_tls_acme_cloudflare_token }}"
