postgresql_client_login_host: localhost
postgresql_client_login_port: 5432
postgresql_client_login_database: postgresql
postgresql_client_login_username: "{{ postgresql_client_login_database }}"
postgresql_client_login_password: "{{ mandatory(msg='default secret') }}"

postgresql_client_database: postgresql
postgresql_client_username: "{{ postgresql_client_database }}"
postgresql_client_password: "{{ mandatory(msg='default secret') }}"

postgresql_client_hba_id: null
postgresql_client_hba_username: postgresql
postgresql_client_hba_rules: []
