$ANSIBLE_VAULT;1.1;AES256
35363962616139343564383566653665616535313231373733666439333961636333353564336133
6665303262333964343066653131396534326562343565380a303362643530353463316439333332
65663762393831353635313035653832613434386134333137326234653331303531653235393637
6362383734316462350a653333666333343338653764373033386630353265376135386231323139
61303932346465666364383962316362343132363634396461353361393363396131643166393739
36313735356339323436393637633162653961303831663138666666616535313436613165616337
31306434626264376539383636656632306236613132656436393665636461356533343538643738
63313536666664326665646233343939613435326463643431343034383566333136356439613762
32616330373935353533656334396633653338323235303161633931353038323035623837333262
34343064353836363331656535343866333235303435623437333663353137303934616539306662
363063383536373865316230333636343464
