$ANSIBLE_VAULT;1.1;AES256
36356665643934613234616264663233383765653432386462373531316466656163356561643435
3638383834353236643138643636336339643739313538300a656532386631346532366166363230
63316166383463643038316338646665306239306561623133326131376133643137353564623731
6230613639376163340a323536613036656465656633326131373338333336666437383437306630
63343632656364356237613966643961646661303461343561663338383034613938636466383664
37333562343539633336353536636239363234326230373763316461333061633936653036386637
36613238626131613038343838306365383831313961353366383266303034656433626631613239
66666463373735313433316532373437376537626330623831376466623430346564313438623363
31373534646231646531393132623033323932663732373866376664306237663837326234393637
30333761343338366333623334333332663537303662313533616539666339623536303762356634
62626338316230656161613637626631623633633835343835663366656335366565313832363935
33373736363661353231313864336263343138393731636235366132643464353363376437373663
62373235653538396337333066333539653531386461336130363938643735623537306331313237
64353430666665653665366331363030653664643033326239663333383336656633616234663532
33653637336137623539326366386332313038626439343638626638366230353834396461626234
36303062386239663538
