postgresql_database: postgres
postgresql_username: postgres
postgresql_password: "{{ vault_postgresql_password }}"
postgresql_repmgr_password: "{{ vault_postgresql_repmgr_password }}"
postgresql_repmgr_node_network_name: "{{ postgresql_repmgr_node_name }}.service.neontech.dev"
postgresql_repmgr_primary_host: postgresql1.service.neontech.dev
postgresql_repmgr_partner_nodes:
  - postgresql1.service.neontech.dev
  - postgresql2.service.neontech.dev
  - postgresql3.service.neontech.dev
  - postgresql4.service.neontech.dev
