$ANSIBLE_VAULT;1.1;AES256
61656438633238366364343032313537366166653732383863666162306462393231613865656135
6435623463626331653766623335343239313034623635650a626564376336646636613631343134
37326664633161373939306335623032303234626236613032353731663933613933346166303130
6265396265386133390a316463383938333763386239643838626566656661316235633035393764
39326635346562313934316230613539333933393438643364333431353165303237336537333439
36346531363436653535353331636534653932303332633765396636323034333531316430613032
64623730396530666662323764613064356436326665386631303835323039393930323536643434
39396436346132373234323835633235343731376662333931326435306133363438653236636232
31653136353633646262363430623239333366356337343666306661323831343432373337376233
37393735353730373462376131613431656633353639386264343664303838343066623239373433
65303935393231656432343439343336613034643836626566333565343666623931663163383433
63383836653538346466353834346638633134373032663233376131383931623464663965303566
30396331336161326438656236666132633766323732333937396438306439326161
