# Default variables are dependent on group variables and repository layout.
# Variables prefixed with lxc_pve are for pve-specific configurations.

# API
lxc_pve_api_host: "{{ pve_api_host }}"
lxc_pve_api_port: "{{ pve_api_port }}"
lxc_pve_api_user: "{{ pve_api_user }}"
lxc_pve_api_token_id: "{{ pve_api_token_id }}"
lxc_pve_api_token: "{{ pve_api_token }}"

# General
lxc_pve_node: "{{ pve_node }}"
lxc_pve_vmid: "{{ mandatory(msg='default value') }}"
lxc_hostname: "{{ mandatory(msg='default value') }}"
lxc_ssh_public_key_file: "{{ 'ssh/{}/{}_root_ed25519.pub'.format(env, lxc_hostname) }}"

# Template
lxc_pve_template: debian-12-standard_12.7-1_amd64.tar.zst
lxc_pve_template_type: vztmpl
lxc_os_type: debian

# Storage
lxc_pve_storage: "{{ pve_storage_shared }}"
lxc_pve_storage_fs: "{{ pve_storage_shared_fs }}"

# Disks
lxc_disk_volume_storage: "{{ lxc_pve_storage }}"
lxc_disk_volume_size: 8 # GiB

# CPU
lxc_cpu_cores: 1

# Memory
lxc_memory: 512 # MB
lxc_memory_swap: 512 # MB

# Network
lxc_pve_interfaces: {}
