# Version
technitium_dns_version: 13.6.0
# Download
technitium_dns_download_filename: DnsServerPortable.tar.gz
technitium_dns_download_checksum: 89614c20fb282050f701bc785681aaf1d45a5208cf313759a093df95606014b7
# User
technitium_dns_user_name: "{{ ansible_user_id }}"
technitium_dns_user_id: "{{ ansible_user_uid }}"
technitium_dns_group_name: "{{ technitium_dns_user_name }}"
technitium_dns_group_id: "{{ technitium_dns_user_id }}"
