# CA
step_ca_host: "{{ ca_host }}"
step_ca_port: "{{ ca_port }}"
step_ca_fingerprint: "{{ ca_fingerprint }}"

# User
step_ca_user_name: ca # LDAP
step_ca_user_id: 2071 # LDAP

# Provisioner
step_ca_provisioner_name: "{{ step_ca_user_name }}"
step_ca_provisioner_password: "{{ vault_step_ca_provisioner_password }}"

# YubiKey
step_ca_yubikey_pin: "{{ vault_step_ca_yubikey_pin }}"
