$ANSIBLE_VAULT;1.1;AES256
66306163383766623935633432396133613735656664656261393035393865633265336135313161
3032386466633735356437623965663930343830376230340a366438626564316630656134343430
64306230353464393861306233663939396431643337376432666531636135356537363530336436
6330613034386463620a343538666131373562386131356137373266316331383530613233346239
62623435653431343262396666303037333463346639633937383565323965393739333439656432
63303639373039396262636238636663366439616331376364366466626331306664353562323933
63393765613932666266306537303530366239323435613163396565613430396230316361306666
36663939343635313139363736616536613735336138626662303131356461393238626337653964
62623764663033663262343563353666373161393435626264386235633666363562303232303961
30326162616465396661663135633730616233306665373336326165633031653561323765383135
62666639393636613435363933313439306537333865306433643436383664333131623863306333
36323631323732386536376662383461633866663930386333613037333764613663643363393634
37353531333666626538393834333138383335653538383432666334363038353139303337353730
35383663303330666362313235656461303230326364613437663839636235326464376261316637
38303436633036383836633065393064616438353630313238323166323137303636333462336438
30326538346638373535643534633537376434656336666638386639346130333536366337356232
32653431303530653933306631326237653865343536313065656366373530336636346263386139
66636234323838623732393434396139656135353833343665623131613836336536616564386132
37333566363234303763306338353537393162666364616265623836343435306234373163333166
63626337316462323762393461316366346461623934386565396436643638316263663831613432
64346337386263626335346165303064363136353739336133386134356262653337626635356566
66363935643432323366373966363163323032613162363264623266323061353935343538633531
38346662363037306335633966363864383364303766656639643264343939646536626465386263
39633365663231336334
