step_ca_version: 0.28.4

step_ca_download_filename: step-ca_{{ step_ca_version }}.tar.gz
step_ca_download_checksum: 44d8e42508cea63c0572408c15e3f52cbbc18a8b3d3df5c213945d5465c56be0

step_ca_user_name: step_ca
step_ca_user_id: 1000

step_ca_dns: [localhost]
step_ca_address: :443

step_ca_provisioner_name: "{{ step_ca_user_name }}"
step_ca_provisioner_password: "{{ mandatory(msg='default secret') }}"
