redis_docker_version: sha256:05dce21160902eb9ffb1d8c6371ee71f30ab5a323277ca9db479181ec25c53fc # 7.4.1
# redis_password
redis_replication_mode: master
redis_master_host: redis
redis_replication_host: redis
