# User
redis_user_name: "{{ ansible_user_id }}"
redis_user_id: "{{ ansible_user_uid }}"
redis_group_name: "{{ redis_user_name }}"
redis_group_id: "{{ redis_user_id }}"

# TLS
redis_tls_ca: null
redis_tls_certificate: /etc/redis/certificates/fullchain.pem
redis_tls_certificate_key: /etc/redis/certificates/privkey.pem
redis_tls_dhparam: /etc/redis/certificates/dhparam.pem
# TLS (ACL)
redis_tls_acl_username: tls
redis_tls_acl_password: null

# ACL
redis_acl_password: null
redis_acl: {}
