redis_server_docker_version: 7.4.1@sha256:33bca304adb3404963e8562c597fc83b800b79d2fbf1ff914bbd4bf1e16e3904
redis_server_step_docker_version: 0.28.2@sha256:dbe894c2d146b7389cc2e1e1d14cccd03f8c765a6eeb957f3340333c2f86a767
# server
redis_server_username: default
redis_server_password: "{{ mandatory(msg='default secret') }}"
# replication
redis_server_replication_mode: master
redis_server_replication_host: localhost
# master
redis_server_master_host: localhost
redis_server_master_port: 6379
# tls
redis_server_tls: false
redis_server_tls_clients: true
redis_server_tls_username: tls
redis_server_tls_password: "{{ mandatory(msg='default secret') }}"
redis_server_tls_domains: localhost
redis_server_tls_ca_host: ca
redis_server_tls_ca_port: 443
redis_server_tls_ca_fingerprint: "{{ mandatory(msg='default value') }}"
redis_server_tls_acme_rfc2136_ip: 127.0.0.1
redis_server_tls_acme_rfc2136_port: 53
redis_server_tls_acme_rfc2136_name: acme
redis_server_tls_acme_rfc2136_secret: "{{ mandatory(msg='default secret') }}"
redis_server_tls_acme_rfc2136_algorithm: HMAC-SHA256

# users.acl
redis_server_administrator_username: administrator
redis_server_administrator_password: "{{ mandatory(msg='default secret') }}"
