- name: Generate locales
  ansible.builtin.command: locale-gen
  changed_when: true

- name: Reconfigure locales
  ansible.builtin.command: dpkg-reconfigure --frontend noninteractive locales
  changed_when: true

- name: Reboot
  ansible.builtin.reboot:
