$ANSIBLE_VAULT;1.1;AES256
61306133613339353462326166356165363137653765353564633635383833636439346136626338
3537623634353336366131316665613666653437366135630a383161313336393338343133396261
63333634316230376562636636616261323132616632346439313264613062356632666330373731
6264643537313431610a323236633863383561376437333834333831343461653330313939646630
35663432666265323338373734313831643666373063616338333139336433393333613231303765
61626531336230393130643633346637393937376663653438656163653562343137653232393034
36633865316663653065366532643763636236643835396437626434343863316439653639323532
39666134316135353234396464373662656538663234313064316533626366643661636162386534
36646330323934623761393962373335316635343939366634373261633934643565373966363161
36393637313863663236373334663566653730303366656231373864376433393736346261616266
62666561316334666565366565313565623561336463363830633638623039316463313166366137
33373564636635396130383037383364343037643039336334353762396635333634383138636630
37333564356533346337333561653733643230383161326139313335356134326362626530363464
62366539323761373739356538646532306537643866396137633332386530646464346264363332
65633430316436653666343265353139366664633065656261333538326239393963356131383939
65323466336664613461
