$ANSIBLE_VAULT;1.1;AES256
61636364343963326631366466333830316162636436323538663866663434663533353334663665
3131306463346432636164393933663938343833666335630a633530623439613538656430313236
34393761303133383361643465386462643738653464666664666635353033333764333531386666
6162643135616536350a623362316639343532653437653262323964643339393666376438613634
65656634323430386264623765336130373265353764646536653161363339383663303539363131
63613465373237636638383538383263313833616164326634623064326261626264353865343864
34393438303635643939313261313634646562343536323863346433333134653663353062336631
31396362353638323035656539653630316563623436366532306263653638396436653562623537
35346535646464623732666561376532333539383466303033333837306535333466376164663537
6134343436663731626432653232333234666630633362626564
